name: "Various daily checks"

on:
  schedule:
    - cron: '34 4 * * *'

jobs:
  el7-devtoolset:
    runs-on: ubuntu-22.04

    steps:
    - name: Check whether a newer devtoolset exists
      run: |
        if docker run --rm centos:7 bash -c 'yum install -y centos-release-scl-rh && yum info devtoolset-12-gcc-c++'
        then
          echo "::warning file=builder-support/dockerfiles/Dockerfile.rpmbuild::A newer devtoolset exists. Please edit builder-support/dockerfiles/Dockerfile.rpmbuild, builder-support/dockerfiles/Dockerfile.rpmbuild, and .github/workflows/dailies.yml"
          exit 1
        else
          echo "::notice ::No newer devtoolset exists (good)"
          exit 0
        fi
